# Generated by Django 2.2.3 on 2019-08-31 18:10

from django.db import migrations, models
import main.utilities


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_additionalimage_bb'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb',
            name='image',
            field=models.ImageField(blank=True, upload_to=main.utilities.get_timestamp_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='contacts',
            field=models.TextField(verbose_name='Контакты'),
        ),
    ]
